import { motion } from 'framer-motion'
import { ArrowRight, BrainCircuit, CheckCircle2, CloudCog, Cpu, Gauge, Network, ShieldCheck, Sparkles, Zap } from 'lucide-react'
import { Link } from 'react-router-dom'
import RouterFlow from '../components/RouterFlow'
import { Panel } from '../components/UI'

export default function LandingPage(){return <div className="landing">
  <nav className="landing-nav"><div className="brand"><div className="brand-mark"><BrainCircuit size={23}/></div><div><strong>RouteForge</strong><span>AMD Developer Hackathon</span></div></div><div className="landing-links"><a href="#system">System</a><a href="#features">Features</a><Link className="btn btn-ghost" to="/overview">Open console</Link></div></nav>
  <section className="hero"><div className="hero-grid"/><motion.div className="hero-copy" initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.7}}><span className="hero-kicker"><Sparkles size={14}/> Hybrid local + cloud inference</span><h1>Every prompt.<br/><span>The right model.</span><br/>Automatically.</h1><p>A self-resilient AI routing gateway that classifies intent, prioritises efficient local SLMs, and escalates to high-capacity cloud models only when the task demands it.</p><div className="hero-actions"><Link className="btn btn-primary btn-lg" to="/playground">Launch AI Playground <ArrowRight size={17}/></Link><Link className="btn btn-ghost btn-lg" to="/architecture">Explore architecture</Link></div><div className="hero-trust"><span><CheckCircle2/>3-tier classification</span><span><CheckCircle2/>Automatic failover</span><span><CheckCircle2/>Cost-aware routing</span></div></motion.div>
  <motion.div className="hero-console" initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} transition={{delay:.2,duration:.7}}><div className="console-bar"><div><i/><i/><i/></div><span>live routing preview</span><em>ONLINE</em></div><div className="prompt-preview">“Optimise this Python data pipeline for GPU execution.”</div><div className="mini-route"><span className="active"><Cpu/> Router SLM</span><b>→</b><span><Network/> Coding policy</span><b>→</b><span><CloudCog/> Qwen Coder</span></div><div className="console-result"><div><strong>CODING</strong><span>classification</span></div><div><strong>1.24s</strong><span>latency</span></div><div><strong>$0.0008</strong><span>estimated cost</span></div></div></motion.div></section>
  <section className="stat-strip"><div><strong>3</strong><span>classification tiers</span></div><div><strong>4</strong><span>task-specialised routes</span></div><div><strong>2×</strong><span>model failover chain</span></div><div><strong>WAL</strong><span>concurrency-safe metrics</span></div></section>
  <section id="system" className="landing-section"><div className="section-title"><span className="eyebrow">THE ROUTING ENGINE</span><h2>Intelligence before inference</h2><p>RouteForge spends the cheapest possible intelligence first, then scales model capacity only when necessary.</p></div><Panel className="landing-flow" glow><RouterFlow active="complete"/></Panel></section>
  <section id="features" className="landing-section"><div className="feature-grid">{[[Cpu,'Local-first efficiency','Run capable tasks on compact Ollama models close to the hardware.'],[Network,'Three-tier resilience','Fine-tuned SLM, semantic vector search, then regex safety fallback.'],[ShieldCheck,'Automatic recovery','Primary model failure triggers a configured fallback without losing the request.'],[Gauge,'Operational observability','Track latency, token usage, cost, savings, fallback rate and model performance.'],[Zap,'Task-aware routing','Dedicated routes for coding, mathematics, research and casual conversation.'],[CloudCog,'Cloud when it matters','Escalate to Fireworks-hosted high-capacity models only when required.']].map(([Icon,t,d])=><Panel key={t} className="feature-card"><div className="feature-icon"><Icon/></div><h3>{t}</h3><p>{d}</p></Panel>)}</div></section>
  <footer className="landing-footer"><div className="brand"><div className="brand-mark"><BrainCircuit/></div><div><strong>RouteForge</strong><span>Built for the AMD Developer Hackathon</span></div></div><span>React · FastAPI · Ollama · ChromaDB · SQLite WAL</span></footer>
</div>}
