import { useEffect, useState } from 'react'
import { Activity, ArrowRight, Bot, CircleDollarSign, Clock3, RefreshCw, ShieldCheck, Zap } from 'lucide-react'
import { Link } from 'react-router-dom'
import { endpoints, normalizeError } from '../api/client'
import { Button, ErrorState, Metric, Page, Panel, Skeleton } from '../components/UI'
import RouterFlow from '../components/RouterFlow'

const fmt=(n,d=0)=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:d})
export default function OverviewPage(){const [data,setData]=useState(null),[health,setHealth]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(null)
 const load=async()=>{setLoading(true);setError(null);try{const [m,h]=await Promise.all([endpoints.metrics(),endpoints.health()]);setData(m.data.aggregated_metrics);setHealth(h.data)}catch(e){setError(normalizeError(e))}finally{setLoading(false)}};useEffect(()=>{load()},[])
 return <Page eyebrow="COMMAND CENTER" title="Routing intelligence at a glance" description="Live operational metrics from the model gateway, cost engine and dependency checks." actions={<Button icon={RefreshCw} variant="ghost" onClick={load}>Refresh</Button>}>
 {error&&<ErrorState error={error} onRetry={load}/>} {loading?<div className="metric-grid">{[1,2,3,4].map(i=><Skeleton key={i} className="metric-skeleton"/>)}</div>:data&&<><div className="metric-grid"><Metric icon={Zap} label="Total requests" value={fmt(data.total_requests)} meta={`${fmt(data.successful_requests)} successful`} tone="cyan"/><Metric icon={Clock3} label="Average latency" value={`${fmt(data.avg_latency_ms)} ms`} meta="End-to-end execution" tone="violet"/><Metric icon={CircleDollarSign} label="Cost saved" value={`$${fmt(data.cost_saved_usd,6)}`} meta={`${fmt(data.savings_pct,1)}% vs baseline`} tone="green"/><Metric icon={ShieldCheck} label="Fallback rate" value={`${fmt((data.fallback_rate||0)*100,1)}%`} meta={`${fmt(data.fallback_count)} recovered requests`} tone="amber"/></div>
 <div className="overview-grid"><Panel className="overview-primary" glow><div className="panel-head"><div><span className="eyebrow">LIVE SYSTEM MAP</span><h2>Hybrid execution pipeline</h2></div><Link to="/router" className="text-link">Open visualizer <ArrowRight size={15}/></Link></div><RouterFlow active="complete"/></Panel>
 <Panel><div className="panel-head"><div><span className="eyebrow">SYSTEM STATUS</span><h2>Dependency health</h2></div><span className={`health-ring ${health?.status}`}/></div><div className="service-list">{Object.entries(health?.services||{}).map(([name,status])=><div className="service-row" key={name}><div className={`service-icon ${status==='connected'||status==='healthy'?'ok':'bad'}`}><Activity size={16}/></div><div><strong>{name.replace(/_/g,' ')}</strong><span>Reported by /health</span></div><b className={status==='connected'||status==='healthy'?'ok-text':'bad-text'}>{status}</b></div>)}</div><Link to="/health" className="btn btn-ghost btn-block">Open health console</Link></Panel></div>
 <div className="overview-grid lower"><Panel><div className="panel-head"><div><span className="eyebrow">TASK DISTRIBUTION</span><h2>Requests by intent</h2></div></div><div className="task-bars">{Object.entries(data.task_type_counts||{}).map(([name,count])=><div key={name}><div><span>{name.replace('_',' ')}</span><strong>{count}</strong></div><div className="bar"><i style={{width:`${Math.max(8,(count/Math.max(...Object.values(data.task_type_counts||{x:1})))*100)}%`}}/></div></div>)}{!Object.keys(data.task_type_counts||{}).length&&<p className="muted">No requests logged yet. Run the playground to generate live metrics.</p>}</div></Panel>
 <Panel className="quick-launch"><div className="quick-icon"><Bot/></div><span className="eyebrow">DEMO READY</span><h2>Route your first prompt</h2><p>See classification, model selection, fallback behaviour, latency, token usage and cost in one polished flow.</p><Link className="btn btn-primary" to="/playground">Launch playground <ArrowRight size={16}/></Link></Panel></div></>}
 </Page>}
