import { useRef, useState } from 'react'
import { Bot, Braces, CircleDollarSign, Clock3, Code2, Eraser, FlaskConical, Gauge, MessageCircle, Send, Sigma, Sparkles, StopCircle, TestTube2, Zap } from 'lucide-react'
import { endpoints, normalizeError } from '../api/client'
import { useApp } from '../context/AppContext'
import RouterFlow from '../components/RouterFlow'
import { Badge, Button, CopyButton, ErrorState, LoadingLabel, Page, Panel } from '../components/UI'

const examples=[{label:'Coding',icon:Code2,prompt:'Write an efficient Python function to detect cycles in a directed graph and explain the time complexity.'},{label:'Math',icon:Sigma,prompt:'Solve 3x² - 14x - 5 = 0 step by step and verify both roots.'},{label:'Research',icon:FlaskConical,prompt:'Summarise the major technical challenges in deploying small language models at the edge.'},{label:'Casual',icon:MessageCircle,prompt:'Give me three creative names for an AI routing platform.'}]
const sleep=(ms)=>new Promise(r=>setTimeout(r,ms))
export default function PlaygroundPage(){const {addActivity}=useApp();const [prompt,setPrompt]=useState(''),[taskType,setTaskType]=useState(''),[stage,setStage]=useState('idle'),[result,setResult]=useState(null),[error,setError]=useState(null);const controller=useRef(null)
 const submit=async(e)=>{e?.preventDefault();if(prompt.trim().length<5)return;setResult(null);setError(null);setStage('classifying');controller.current=new AbortController();try{await sleep(450);setStage('routing');await sleep(400);setStage('executing');const r=await endpoints.process({prompt:prompt.trim(),...(taskType?{task_type:taskType}:{})},controller.current.signal);setResult(r.data);setStage('complete');addActivity({prompt:prompt.trim(),...r.data})}catch(e){setError(normalizeError(e));setStage('idle')}}
 const reset=()=>{setPrompt('');setTaskType('');setResult(null);setError(null);setStage('idle')};const cancel=()=>controller.current?.abort()
 return <Page eyebrow="PRIMARY DEMO" title="AI Routing Playground" description="Submit a prompt and watch RouteForge classify, route, execute and measure the request in real time.">
  <div className="playground-grid"><div className="playground-main"><Panel glow className="composer"><div className="composer-top"><div><Sparkles size={17}/><strong>Prompt composer</strong></div><span>{prompt.length}/8000</span></div><form onSubmit={submit}><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Ask a coding, mathematics, research or conversational question…" rows={8}/><div className="composer-bottom"><select value={taskType} onChange={e=>setTaskType(e.target.value)} aria-label="Task override"><option value="">Auto classify</option><option value="coding">Coding</option><option value="math">Math</option><option value="research">Research</option><option value="casual_chat">Casual chat</option></select><div className="composer-actions"><Button type="button" variant="ghost" icon={Eraser} onClick={reset}>Clear</Button>{['classifying','routing','executing'].includes(stage)?<Button type="button" variant="danger" icon={StopCircle} onClick={cancel}>Cancel</Button>:<Button type="submit" icon={Send} disabled={prompt.trim().length<5}>Route prompt</Button>}</div></div></form></Panel>
  <div className="example-row">{examples.map(({label,icon:Icon,prompt:p})=><button key={label} onClick={()=>setPrompt(p)}><Icon size={15}/>{label}</button>)}</div>
  {error&&<ErrorState error={error} onRetry={submit}/>} {stage!=='idle'&&!result&&<Panel className="route-progress"><div className="progress-head"><LoadingLabel text={stage==='classifying'?'Classifying intent':stage==='routing'?'Evaluating routing policy':'Executing selected model'}/><span>Live request flow</span></div><RouterFlow active={stage}/></Panel>}
  {result&&<Panel className="response-panel" glow><div className="response-head"><div><Badge tone="success">{result.status}</Badge><span>{result.request_id}</span></div><CopyButton text={result.result}/></div><div className="response-content"><pre>{result.result}</pre></div><div className="response-meta"><div><Bot/><span>Model</span><strong>{result.metadata.final_model_used}</strong></div><div><Clock3/><span>Latency</span><strong>{result.metadata.latency_ms} ms</strong></div><div><Gauge/><span>Tokens</span><strong>{result.tokens.total}</strong></div><div><CircleDollarSign/><span>Cost</span><strong>${Number(result.cost.usd).toFixed(6)}</strong></div><div><Zap/><span>Task</span><strong>{result.metadata.task_type.replace('_',' ')}</strong></div><div><TestTube2/><span>Fallback</span><strong>{result.metadata.fallback_model_used?'Activated':'Not needed'}</strong></div></div></Panel>}</div>
  <aside className="playground-side"><Panel><span className="eyebrow">ROUTING CONTRACT</span><h3>What the API returns</h3><ul className="check-list"><li><Bot/>Exact model used</li><li><Clock3/>End-to-end latency</li><li><Gauge/>Input and output tokens</li><li><CircleDollarSign/>Estimated USD cost</li><li><Zap/>Detected task category</li><li><Braces/>Primary/fallback outcome</li></ul></Panel><Panel><span className="eyebrow">CLASSIFIER</span><h3>Three resilient tiers</h3><div className="tier-list"><div><b>01</b><span><strong>Fine-tuned SLM</strong><small>Llama-3.2-1B router</small></span></div><div><b>02</b><span><strong>Semantic vector match</strong><small>ChromaDB + embeddings</small></span></div><div><b>03</b><span><strong>Regex safety fallback</strong><small>Guaranteed classification</small></span></div></div></Panel></aside></div>
 </Page>}
